const data = [
    {
        area: "CORP - RECURSOS HUMANOS",
        employeeName: "ELISEO",
        employeeNumber: "50056",
        employeeSurname: "PEREZ GONZALEZ",
        evaluationName: "Auto evaluación (Periodo 2018-2)",
        id: 278,
        includePastObjectives: true,
        isAutoEvaluation: true,
        region: "CORPORATIVO",
        status: 2,
    },
    {
        employeeNumber: "50083",
        employeeName: "BEATRIZ",
        employeeSurname: "MARQUEZ GOMEZ",
        region: "CORPORATIVO",
        area: "CORP - RECURSOS HUMANOS",
        evaluationName: "Auto evaluación (Periodo 2018-2)",
        isAutoEvaluation: true,
        includePastObjectives: true,
        status: 2,
        id: 279,
    },
    {
        employeeNumber: "50213",
        employeeName: "JHOJANCIE",
        employeeSurname: "PEREZ AGUILAR",
        region: "CORPORATIVO",
        area: "CORP - RECURSOS HUMANOS",
        evaluationName: "Auto evaluación (Periodo 2018-2)",
        isAutoEvaluation: true,
        includePastObjectives: true,
        status: 2,
        id: 280,
    },
    {
        employeeNumber: "50328",
        employeeName: "MARIA GUADALUPE",
        employeeSurname: "JIMENEZ LOPEZ",
        region: "CORPORATIVO",
        area: "CORP - RECURSOS HUMANOS",
        evaluationName: "Auto evaluación (Periodo 2018-2)",
        isAutoEvaluation: true,
        includePastObjectives: true,
        status: 2,
        id: 281,
    },
    {
        employeeNumber: "50930",
        employeeName: "CRISTIAN RAFAEL",
        employeeSurname: "GARCIA CARRANZA",
        region: "CORPORATIVO",
        area: "CORP - RECURSOS HUMANOS",
        evaluationName: "Auto evaluación (Periodo 2018-2)",
        isAutoEvaluation: true,
        includePastObjectives: true,
        status: 1,
        id: 288,
    },
];

export default data;
